### ISSUE TITLE
Electrod protected keywords

### ISSUE THREAD

**Issue by nmacedo** [haslab/Pardinus#30]
`next` is protected in electrod and throws a syntax error; which other keywords must be renamed?

**Comment by grayswandyr** [comment]
I don't remember why `next` is reserved actually. For your testing, as you build Electrod yourself IIRC, you may comment lines 78-79 in `src/Scanner.mll` and that should do it.
The full list of keywords is actually in this very file, starting [here](https://github.com/grayswandyr/electrod/blob/master/src/Scanner.mll#L67).
